name "ckan"
description "Installs and configures CKAN for development."
version "0.1.0"
maintainer "Braulio Chavez"
maintainer_email "braulio@codeandomexico.org"
license "Apache v2.0"
depends "git"
depends "python"
depends "postgresql"
depends "java"
depends "apache2"
depends "line"
